on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
  
jobs:
  deploy:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: executing git pull, collectstatic and restart server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.DO_PRIVATE_KEY }}
        passphrase: ${{ secrets.DO_PASSPHRASE }}
        port: 22
        script: |
          cd ${{ secrets.WORK_DIR }} && \
          git checkout ${{ secrets.MAIN_BRANCH }} && \
          git pull && \ 
          echo yes | python3 manage.py collectstatic && \ 
          sudo systemctl restart gunicorn