on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
  
jobs:
  deploy:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.DO_PRIVATE_KEY }}
        port: 22
        script: whoami